#!/bin/bash

# 
# Copyright (c) 2019 Artur Meski
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# 

echo
echo " ------------------------------------------------"
echo " -- ReactICS -- Reaction Systems Model Checker --"
echo " ------------------------------------------------"
echo

mode="$1"
shift

REACTICS_BDD="$(pwd)/reactics-bdd"
REACTICS_SMT="$(pwd)/reactics-smt"

if [[ "$mode" == "bdd" ]]
then
  
  if [[ ! -x $REACTICS_BDD/reactics ]]
  then
    echo "Make sure to run setup first!"
  fi
  
  reactics-bdd/reactics $*
  
elif [[ "$mode" == "smt" ]]
then
 
  export PYTHONPATH="$PYTHONPATH:$REACTICS_SMT"
  if [[ "$*" != "" ]]
  then
    python3 $* 
  else
    echo "Nothing to do"
  fi
  
elif [[ "$mode" == "setup" ]]
then
 
  git pull 
  cd $REACTICS_BDD
  ./build_cudd.sh
  make

else
  
  echo "Usage: $0 <mode> <module-specific parameters>"
  echo
  echo "mode:"
  echo "  - bdd    -- uses BDD-based module"
  echo "  - smt    -- used SMT-based module"
  echo "  - setup  -- builds what is required" 
  echo
  
fi

# EOF
